export const SET_ACTIVE_PROBLEM = 'SET_ACTIVE_PROBLEM';
export const SET_ACTIVE_THEME = 'SET_ACTIVE_THEME';
export const SET_ACIVE_LEVEL = 'SET_ACTIVE_LEVEL';
export const SET_LOADING_STATUS = 'SET_LOADING_STATUS';

export const SET_START_STATUS = 'SET_START_STATUS';
export const SET_START_OVER_STATUS = 'SET_START_OVER_STATUS';
export const SET_PAUSE_STATUS = 'SET_PAUSE_STATUS';
export const SET_PREPARE_STATUS = 'SET_PREPARE_STATUS';

export const SET_ACTIVE_STORY = 'SET_ACTIVE_STORY';
export const FETCH_ALL_STORIES = 'FETCH_ALL_STORIES';
export const SET_STORY_LIST = 'SET_STORY_LIST';
export const TEMP_ACTIVE_STORY = 'TEMP_ACTIVE_STORY';
export const SET_STORIES_TOTAL_NUMBER = 'SET_STORIES_TOTAL_NUMBER';
export const UPDATED_STORY_LIST = 'UPDATED_STORY_LIST';


export const SET_ACTIVE_MODAL_ID = 'SET_ACTIVE_MODAL_ID';

